services:
  data-source:
    container_name: data-source
    image: postgres:13
    environment:
       POSTGRES_USER: postgres 
       POSTGRES_PASSWORD: postgres 
       POSTGRES_DB: postgres
    ports:
      - 5434:5434
    volumes:
      - pgdata:/var/lib/postgresql/data


volumes:
  pgdata: {}